group_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from renova import views

urlpatterns = [
    path('', views.index, name='index.html'),
    path('accounts/', include('registration.backends.simple.urls')),
    path('admin/', admin.site.urls),
    path('renova/', include('renova.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

renova/urls.py
from django.urls import path
from renova import views

app_name = "renova"

urlpatterns = [
    path('', views.index, name='index'),
    path('faq/', views.faq, name='faq'),
    path('about-us/', views.about_us, name='about_us'),
    path('my-logs/', views.my_logs, name='my_logs'),
    path('my-logs/record-log/', views.record_log, name='record_log'),
    path('my-account/', views.my_account, name='my_account'),
    path('groups/', views.groups, name='groups'),
    path('groups/make-group/', views.make_group, name='make_group'),
    path('groups/<slug:group_name_slug>/', views.group, name='group'),
    path('groups/<slug:group_name_slug>/leave', views.leave_group, name='leave_group'),
    path('groups/<slug:group_name_slug>/join', views.join_group, name='join_group'),
    path('groups/<slug:group_slug>/remove_member/<str:username>/', views.remove_member, name='remove_member'),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('delete_account/', views.delete_account, name='delete_account'),
    path('groups/<slug:group_slug>/edit/', views.edit_group_attributes, name='edit_group_attributes'),
]

renova/models.py
from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    picture = models.ImageField(upload_to='profile_images', blank = True, default='profile_images/default.jpg')

    target_calories = models.IntegerField(default=2000)
    target_water = models.IntegerField(default=2500)  # milliliters
    target_sleep = models.IntegerField(default=8)  # hours
    target_duration = models.IntegerField(default=60)  # minutes

    def __str__(self):
        return self.user.username


class Group(models.Model):
    name = models.CharField(max_length=255, unique=True, primary_key=True)
    admin = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    members = models.ManyToManyField(User, related_name='member_groups', blank=True)
    creation_date = models.DateField(default=timezone.now)
    icon = models.ImageField(upload_to='group_icons', blank=True)
    activities = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    announcements = models.TextField(blank=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)

        super().save(*args, **kwargs)
        if not self.members.exists():
            self.members.add(self.admin)

    def remove_member(self, user):
        self.members.remove(user)

    def __str__(self):
        return self.name


class Comment(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    creation_date = models.DateField(default=timezone.now)
    likes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.text


class Activity(models.Model):
    name = models.CharField(max_length=200)
    duration = models.IntegerField()
    log = models.ForeignKey('Log', related_name='activities', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name


class Log(models.Model):
    creation_date = models.DateField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total_duration = models.IntegerField(default=0)
    water = models.IntegerField(default=0)
    calories = models.IntegerField(default=0)
    sleep = models.IntegerField(default=0)

    def __str__(self):
        return str(self.pk)

renova/forms.py
#It's platonic in here
from django import forms
from renova.models import User, UserProfile, Group, Log, Activity, Comment

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name', 'activities', 'description', 'announcements', 'icon']


class LogForm(forms.ModelForm):
    water = forms.IntegerField(required=False, initial=0)
    calories = forms.IntegerField(required=False, initial=0)
    sleep = forms.IntegerField(required=False, initial=0)

    class Meta:
        model = Log
        fields = ['water', 'calories', 'sleep']


class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ['name', 'duration']


class CommentForm(forms.ModelForm):
    text = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Enter your comment here...'})
    )
    class Meta:
        model = Comment
        fields = ['text']


class GroupEditForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['description', 'announcements']

renova/views.py
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, HttpResponseForbidden
from django.contrib import messages
from django.db.models import Count
from django.db.models import Sum

from registration.views import RegistrationView

from renova.models import *
from renova.forms import *



def index(request):
    context_dict = {}
    context_dict['summary'] = """Welcome to Renova, your personal haven for holistic wellbeing tracking and community engagement.
    Seamlessly log and monitor your daily activities, calories, hydration, and sleep.
    Dive into Groups where users share activity guides, fostering a supportive community.
    Renova empowers you to achieve optimal health.
    With personalized daily milestones, hit your targeted goals and dream physique.
    Receive activity recommendations aligned with your objectives and engage 
    with others through Groups and interact with likes and comments."""
    # Replace newlines with <br>
    context_dict['summary'] = context_dict['summary'].replace('\n', '<br />')

    context_dict['group_summary'] = """groups within Renova serve as hubs for knowledge sharing, 
    motivation, and collective progress. 
    Whether users want to explore new activities, seek advice, or simply connect with others, 
    participating in groups enhances their overall wellbeing journey. 
    Encourage users to explore existing groups or create their own 
    to maximize the benefits of community engagement!"""
    # Replace newlines with <br>
    context_dict['group_summary'] = context_dict['group_summary'].replace('\n', '<br />')
    
    return render(request, 'renova/index.html', context=context_dict)

def faq(request):
    return render(request, 'renova/faq.html')

def about_us(request):
    context_dict = {}

    context_dict['mission_summary'] = """At Renova, our mission is to empower individuals to take control of their health and wellbeing. 
    We believe that optimal health is a holistic endeavor, encompassing not just physical fitness, but also mental and emotional wellbeing.
    We aim to provide a platform where users can seamlessly log and monitor their daily activities, calories, hydration, and sleep. 

    Our personalized daily milestones are designed to help users achieve their targeted goals and desired physique.
    But we're not just about individual health. We understand the power of community in promoting wellbeing. 
    That's why we've created Groups, a space where users can share activity guides and support each other on their health journeys.

    We're also committed to providing tools for users to visualize their overall wellbeing through a holistic scoring system. 
    This allows users to track their progress and see the impact of their efforts in real-time.
    In addition, we recognize the importance of adaptability in health and fitness. 
    That's why we offer activity recommendations that align with users' objectives, whether they're looking to lose weight, gain weight, or maintain their current physique.

    At Renova, we're not just building a platform, we're building a community. 
    A community that supports, encourages, and empowers each other to achieve optimal health. 
    Join us on this journey to holistic wellbeing. Together, we can achieve more."""
    # Replace newlines with <br>
    context_dict['mission_summary'] = context_dict['mission_summary'].replace('\n', '<br />')

    context_dict['enquiries_email'] = "enquiries@renova.com"
    context_dict['partnerships_email'] = "partnerships@renova.com"
    context_dict['phone_number'] = "+44 7123456789"

    context_dict['youtube'] = "youtube.com/renova"
    context_dict['facebook'] = "facebook.com/renova"
    context_dict['instagram'] = "instagram.com/renova"
    context_dict['twitter'] = "twitter.com/renova"

    return render(request, 'renova/about_us.html', context=context_dict)

@login_required
def my_logs(request):
    logs = Log.objects.all().filter(user=request.user).order_by("-creation_date")
    today_logs = Log.objects.all().filter(user=request.user).filter(creation_date=timezone.now())
    total_water = today_logs.aggregate(Sum('water'))['water__sum'] or 0
    total_calories = today_logs.aggregate(Sum('calories'))['calories__sum'] or 0
    total_sleep = today_logs.aggregate(Sum('sleep'))['sleep__sum'] or 0
    total_duration = today_logs.aggregate(total_duration=Sum('total_duration'))['total_duration'] or 0

    # Get the goals from the user's profile
    user_profile = UserProfile.objects.get(user=request.user)
    target_calories = user_profile.target_calories
    target_water = user_profile.target_water
    target_sleep = user_profile.target_sleep
    target_duration = user_profile.target_duration

    context_dict = {
        'logs' : logs,
        'total_water': total_water,
        'total_calories': total_calories,
        'total_sleep': total_sleep,
        'total_duration': total_duration,
        'target_calories': target_calories,
        'target_water': target_water,
        'target_sleep': target_sleep,
        'target_duration': target_duration,
    }

    return render(request, 'renova/my_logs.html', context=context_dict)


@login_required
def record_log(request):
    activity_form = ActivityForm(request.POST or None)
    log_form = LogForm(request.POST or None, initial={'water': 0, 'calories': 0, 'sleep': 0})
    
    if request.method == 'POST':
        form_name = request.POST.get('form_name')
        if form_name == 'activity_form':
            if activity_form.is_valid():
                # Don't save the activity yet, just store the form data in the session
                activity_data = activity_form.cleaned_data
                activities = request.session.get('activities', [])
                activities.append(activity_data)
                request.session['activities'] = activities
                
                activity_form = ActivityForm()  # Clear the form
                messages.success(request, "Activity added! Save with 'Add Log' when done.")
            else:
                messages.error(request, 'Please fill in both fields: name and duration.')
        elif form_name == 'log_form' and log_form.is_valid():
            # Create a new log
            log = log_form.save(commit=False)
            log.user = request.user
            log.creation_date = timezone.now()
            log.save()  # Save the log before adding activities
            
            # Add the activities from the session to the log
            activities = request.session.get('activities', [])
            for activity_data in activities:
                activity = Activity(log=log, **activity_data)
                activity.save()
                log.total_duration += activity.duration

            log.save()  # Save the log after adding activities
            request.session['activities'] = []  # Clear the activities
            return redirect(reverse('renova:my_logs'))

    return render(request, 'renova/record_log.html', {'log_form': log_form, 'activity_form': activity_form})


@login_required
def my_account(request):
    user_profile, created = UserProfile.objects.get_or_create(user=request.user)
    if created:
        user_profile.picture = 'profile_images/default.jpg'
        user_profile.save()
        if request.method == 'GET':
            return redirect('renova:index')  # Redirect to index after UserProfile creation

    if request.method == 'POST':
        user_profile_form = UserProfileForm(request.POST, request.FILES, instance=request.user.userprofile)
        if user_profile_form.is_valid():
            user_profile_form.save()
            return redirect('renova:my_logs')  # Redirect to my_logs after form submission
            
    else:
        user_profile_form = UserProfileForm(instance=request.user.userprofile)

    return render(request, 'renova/my_account.html', {'user_profile_form': user_profile_form})



@login_required
def delete_account(request):
    if request.method == 'POST':
        # Log the user out (optional but recommended)
        request.user.delete()  # Delete the user account
        return redirect(reverse(index))  # Redirect to the homepage

    return render(request, 'renova/delete_account.html')  # Confirmation page


def groups(request):
    popular_groups = Group.objects.annotate(num_members=Count('members')).order_by('-num_members')[:5]
    recent_groups = Group.objects.order_by('creation_date')[:5]
    all_groups = Group.objects.all()

    context_dict = {}
    context_dict['popular_groups'] = popular_groups
    context_dict['recent_groups'] = recent_groups
    context_dict['all_groups'] = all_groups
    context_dict['make_group_summary'] = """Creating a group within Renova empowers you to take charge of your wellbeing journey. 
    Here's why you might want to start your own group:

    Shared Interests: Connect with others who share your passion
     — whether it's fitness, nutrition, or mindfulness.

    Accountability: Set collective goals and motivate each other to stay on track.

    Curated Content: Share valuable insights and personalized recommendations.

    Community Building: Engage in discussions and celebrate achievements together.

    Event Planning: Organize virtual meetups, challenges, and workshops.

    Safe Space: Create an inclusive environment where everyone feels welcome.
    
    Ready to inspire others? Start your group today! 🌟"""
    # Replace newlines with <br>
    context_dict['make_group_summary'] = context_dict['make_group_summary'].replace('\n', '<br />')

    return render(request, 'renova/groups.html', context=context_dict)

@login_required
def group(request, group_name_slug=None):
    context_dict = {}
    
    try:
        group = Group.objects.get(slug=group_name_slug)
        context_dict['group'] = group

templates/renova/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load renova_template_tags %}

<html>
	<head lang="en">
		<meta charset="UTF-8" />
		<title>Renova -
			{% block title_block %}
				Renovate your health
			{% endblock %}
		</title>
	</head>
	
	<body>
		<div>
			{% block body_block %}
			{% endblock %}
		</div>
		<div>
			{% block sidebar_block %}
				{% get_category_list category%}
			{% endblock %}
		</div>
		<hr />
		<div>
			<ul>
			{% if user.is_authenticated %}
				<!-- Show these links when the user is logged in -->
				<li><a href="{% url 'renova:my_logs' %}">My Logs</a></li>
                <li><a href="{% url 'renova:my_account' %}">My Account</a></li>
				<li><a href="{% url 'renova:logout' %}">Logout</a></li>
			{% else %}
				<!-- Show these links when the user is NOT logged in -->
				<li><a href="{% url 'renova:register' %}">Sign Up</a></li>
				<li><a href="{% url 'renova:login' %}">Login</a></li>
			{% endif %}
				<!-- Outside the conditional statements, ALWAYS show -->
                <li><a href="{% url 'renova:groups' %}">Groups</a></li>
				<li><a href="{% url 'renova:about_us' %}">About Us</a></li>
                <li><a href="{% url 'renova:faq' %}">FAQ</a></li>
				<li><a href="{% url 'renova:index' %}">Home</a></li>
			</ul>
		</div>
	</body>
</html>

templates/renova/faq.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
FAQ
{% endblock %}

{% block js %}
<script src="{% static 'javascript/faq.js' %}"></script>
{% endblock %}

{% block content %}
<div class="middle columns">
	<h1>FAQ</h1> 

    <div>
        <h2>What can we help you find?</h2>
        <select id="faq-dropdown" name="faq-dropdown">
            <option value="">Please select</option>
            <option value="Change my password">Change my password</option>
            <option value="View my activity history">View my activity history</option>
            <option value="What kind of activities can I log in Renova?">What kind of activities can I log in Renova?</option>
            <option value="Delete my account">Delete My Account</option>
        </select>
        <p id="faq-response"></p>
    </div>

    <div id="faq-response"></div>

</div>

<div class="leftalign columns">
    <h2>Popular Questions</h2>

    <div class="faq-questions">
        <ul>
            <li><strong>How do I reset my password if I've forgotten it?</strong></li>
            <li><strong>How can I view my activities?</strong></li>
            <li><strong>What kind of activities can I log?</strong></li>
            <li><strong>How can I remove my account?</strong></li>
        </ul>
    </div>
</div>

<div class="rightalign columns">
    <h2>Can't find what you're looking for?</h2>
    <p>Contact us, through the contact information provided in our 'About Us' page</p>
    <a href="{% url 'renova:about_us' %}">About Us</a>
</div>

{% endblock %}

templates/renova/group.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {% if group %}
        {{ group.name }}
    {% else %}
        Unknown Group
    {% endif %}
{% endblock %}

{% block content %}
    {% if group %}
        <div class="container">
            <div class="columns">
                <div id="group-logo">
                    {% if group.icon %}
                        <img src="{{ group.icon.url }}" alt="{{ group.name }} Icon">
                    {% else %}
                        <img alt="{{ group.name }} Icon">
                    {% endif %}
                    <h1>{{ group.name }}</h1>
                </div>

                <div id="group-description">
                    <p>{{ group.description }}</p>
                </div>

                <div id="group-announcements">
                    <h2>Announcements</h2>
                    <p>{{ group.announcements }}</p>
                </div>

                {% if request.user == group.admin %}
                    <div class="member-section">
                        <h2>Members</h2>
                        {% for member in group.members.all %}
                            {% if member != group.admin %}
                                <div class="member">
                                    <!-- Display member information -->
                                    <p>{{ member.username }}</p>
                                    <form method="post" action="{% url 'renova:remove_member' group.slug member.username %}">
                                        {% csrf_token %}
                                        <button type="submit">Remove Member</button>
                                    </form>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="columns">
                        <a href="{% url 'renova:edit_group_attributes' group.slug %}">Edit Group attributes</a>

                    </div>
                {% endif %}
            </div>

            <div class="comment-section columns rightalign leftline">
                <b><div class="leftalign">Comments</div></b>

                {% for comment in group.comments.all %}
                    <div class="comment">
                        <br>
                        <br>
                        <div class="comment-user">
                            <img class="profile-pic" src="{{ comment.user.userprofile.picture.url }}" alt="{{ comment.user.username }}'s Profile Picture" width="30" height="30">
                            <strong>{{ comment.user.username }}</strong>{% if comment.user == group.admin %} (Admin){% else %} (Member){% endif %}
                        </div>
                        <div class="comment-text">
                            {{ comment.text }}
                        </div>
                        {% if request.user == group.admin %}
                            <form method="post" action="{% url 'renova:delete_comment' comment.id %}">
                                {% csrf_token %}
                                <button type="submit" class="delete-comment">Delete Comment</button>
                            </form>
                        {% endif %}
                    </div>
                {% endfor %}

                
                {% if request.user == group.admin or request.user in group.members.all %}
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="submit-comment">Post comment</button>
                    </form>
                {% endif %}
            </div>

            {% if request.user == group.admin %}
                <p>You are the admin of this group.</p>
            {% elif request.user in group.members.all %}
                <form method="post" action="{% url 'renova:leave_group' group.slug %}">
                    {% csrf_token %}
                    <button type="submit">Leave Group</button>
                </form>
            {% else %}
                <form method="post" action="{% url 'renova:join_group' group.slug %}">
                    {% csrf_token %}
                    <button type="submit">Join Group</button>
                </form>
            {% endif %}

        </div>

    {% else %}
        <p>Group not found.</p>
    {% endif %}
{% endblock %}

templates/renova/groups.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Groups
{% endblock %}

{% block content %}
<div>
	<h1>Groups</h1> 
</div>

<div class="container">
    <div class="columns">
        <section class="leftalign">
            <h2>Explore Groups</h2> 

            <!-- Search box -->
            <input type="text" id="groupSearch" onkeyup="filterGroups()" placeholder="Search for groups..">

            <!-- Scrollable div with links to all groups -->
            <div id="groupList" style="height:300px;overflow:auto;">
                {% for group in all_groups %}
                    <a href="{% url 'renova:group' group.slug %}">{{ group.name }}</a><br>
                {% endfor %}
            </div>

            <h3>Most Popular</h3>
            {% if popular_groups %}
                <ol>
                {% for group in popular_groups %}
                    <li><a href="{% url 'renova:group' group.slug %}">{{ group.name }}</a></li>
                {% endfor %}
                </ol>
            {% else %}
                <strong>There are no groups present.</strong>
            {% endif %}

            <h3>Recently Added</h3>
            {% if recent_groups %}
                <ol>
                {% for group in recent_groups %}
                    <li><a href="{% url 'renova:group' group.slug %}">{{ group.name }}</a></li>
                {% endfor %}
                </ol>
            {% else %}
                <strong>There are no new groups present.</strong>
            {% endif %}
        </section>
    </div>

    <section id="explore-groups" class="rightalign leftline">
        <div class="summaries">
            <h2><a href="{% url 'renova:make_group' %}">Make A Group</a></h2> 
            <p>{{ make_group_summary|safe }}</p>  
        </div>
    </section>
</div>

<!-- JavaScript to filter groups -->
{% block js %}
<script src="{% static 'javascript/filter_groups.js' %}"></script>
{% endblock %}

{% endblock %}

templates/renova/my_account.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
My Account
{% endblock %}

{% block content %}
<div class="container">
	<div class="login-form columns">
		<h1>My Account</h1> 
		<img class="profile-pic profile-pic-rounded" src="{{ request.user.userprofile.picture.url|default:'media/profile_images/default.jpg' }}" width="100" height="100">
		
		<form action="{% url 'registration_register' %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<label for="username">Username:</label>
			<input type="text" id="username" name="username"><br>
			<label for="email">Email Address:</label>
			<input type="text" id="email" name="email"><br>
			<label for="password">Password:</label>
			<input type="password" id="password" name="password"><br>
				<form action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}

					

					<form action="{% url 'renova:my_account' %}" method="post" enctype="multipart/form-data">

						<label for="id_goal_calories">Goal Calories (kcal):</label>
						<input type="number" id="target_calories" name="target_calories" value="{{ request.user.userprofile.target_calories }}"><br>

						<label for="id_goal_water">Goal Water (ml):</label>
						<input type="number" id="target_water" name="target_water" value="{{ request.user.userprofile.target_water }}"><br>

						<label for="id_goal_sleep">Goal Sleep (hours):</label>
						<input type="number" id="target_sleep" name="target_sleep" value="{{ request.user.userprofile.target_sleep }}"><br>

						<label for="id_goal_active_duration">Goal Active Duration (minutes):</label>
						<input type="number" id="target_duration" name="target_duration" value="{{ request.user.userprofile.target_duration }}"><br>
						
						
						<input type="submit" value="Update Targets">

					</form>
					
					{{ user_profile_form.as_p }}
					
					<input type="submit" value="Save Profile Picture">
					
				</form>
			<input type="submit" value="Save Changes">
			<input type="submit" value="Discard Changes">
		</form>
	</div>
	<a href="{% url 'renova:delete_account' %}" class="delete-account rightalign leftline" onclick="return confirm('Are you sure you want to delete your account?')">Delete Account</a>
</div>
{% endblock %}

templates/renova/my_logs.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
My Logs
{% endblock %}

{% block js %}
<script>
  // ---------------------------------------------
  // HARDCODED TARGETS ATM
  // ---------------------------------------------
  var target_calories = "{{ target_calories }}";
  var target_water = "{{ target_water }}";
  var target_sleep = "{{ target_sleep }}";
  var target_duration = "{{ target_duration }}";
  // ---------------------------------------------

  var total_calories = "{{total_calories}}";
  var total_water = "{{total_water}}";
  var total_sleep = "{{total_sleep}}";
  var total_duration = "{{total_duration}}";
</script>
<script src="{% static 'javascript/my_logs.js' %}"></script>
{% endblock %}

{% block content %}

<div class="my_logs middle">

  <div class="large-dial-container">
    <div class="dial-label">OVERALL</div>
    <div id="overall-dial" class="dial large-dial"><div class="dial-text"><strong>0</strong><br />/100</div></div>
  </div>


  <div class="small-dials-container">

    <div class="dial-container">
      <div class="dial-label">Calories</div>
      <div id="calorie-dial" class="dial"><div class="dial-text"><strong>{{ total_calories }}</strong><br />kcal</div></div>
    </div>

    <div class="dial-container">
      <div class="dial-label">Water</div>
      <div id="water-dial" class="dial"><div class="dial-text"><strong>{{ total_water }}</strong><br />ml</div></div>
    </div>

    <div class="dial-container">
      <div class="dial-label">Sleep</div>
      <div id="sleep-dial" class="dial"><div class="dial-text"><strong>{{ total_sleep }}</strong><br />hrs</div></div>
    </div>

    <div class="dial-container">
      <div class="dial-label">Active Duration</div>
      <div id="duration-dial" class="dial"><div class="dial-text"><strong>{{ total_duration }}</strong><br />mins</div></div>
    </div>
  </div>

  <div class="smallercont"><a href="{% url 'renova:record_log' %}">Record a Log</a></div>

</div>

<div class="middle columns">
  {% for log in logs %}
    {% for activity in log.activities.all %}
      <div class="activity-log">
        <div class="activity-name">
          <span>Activity Name: {{ activity.name }}</span>
        </div>
        <div class="activity-duration">
          <span>Duration mins: {{ activity.duration }}</span>
        </div>
      </div>
    {% endfor %}
  {% empty %}
    <div class="activity-log"></div>
    <p>You have no logs at the moment.</p>
  {% endfor %}
</div>


<div class="manage-account-container"><a href="{% url 'renova:my_account' %}">Manage Account</a></div>

{% endblock %}

templates/renova/record_log.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Record Log
{% endblock %}

{% block content %}
<div class="forms-container">
    <form method="post" class="log-form">
        {% csrf_token %}
        <input type="hidden" name="form_name" value="log_form">
        <div class="login-form">
            <div class="form-field">
                <label for="id_calories">Calories (kcal):</label>
                <input id="id_calories" type="number" value="0" name="calories" />
            </div>
            <div class="form-field">
                <label for="id_water">Water (ml):</label>
                <input id="id_water" type="number" value="0" name="water" />
            </div>
            <div class="form-field">
                <label for="id_sleep">Sleep (hours):</label>
                <input id="id_sleep" type="number" value="0" name="sleep" />
            </div>
            <input type="submit" value="Add Log">
        </div>
    </form>

    <form method="post" class="activity-form">
        {% csrf_token %}
        <input type="hidden" name="form_name" value="activity_form">

        {% for message in messages %}
            <div class="alert {{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
        
        <div>
            <label for="id_name">Activity Name:</label>
            <input id="id_name" type="text" name="name" />
    
            <label for="id_duration">Duration (minutes):</label>
            <input id="id_duration" type="number" name="duration" />
            <input type="submit" value="Add Activity">
        </div>
    </form>
</div>
{% endblock %}