group_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from renova import views

urlpatterns = [
    path('', views.index, name='index.html'),
    path('accounts/', include('registration.backends.simple.urls')),
    path('admin/', admin.site.urls),
    path('renova/', include('renova.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

renova/urls.py
from django.urls import path
from renova import views

app_name = "renova"

urlpatterns = [
    path('', views.index, name='index'),
    path('faq/', views.faq, name='faq'),
    path('about-us/', views.about_us, name='about_us'),
    path('my-logs/', views.my_logs, name='my_logs'),
    path('my-logs/record-log/', views.record_log, name='record_log'),
    path('my-account/', views.my_account, name='my_account'),
    path('groups/', views.groups, name='groups'),
    path('groups/make-group/', views.make_group, name='make_group'),
    path('groups/<slug:group_name_slug>/', views.group, name='group'),
    path('groups/<slug:group_name_slug>/leave', views.leave_group, name='leave_group'),
    path('groups/<slug:group_name_slug>/join', views.join_group, name='join_group'),
    path('groups/<slug:group_slug>/remove_member/<str:username>/', views.remove_member, name='remove_member'),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('delete_account/', views.delete_account, name='delete_account'),
    path('groups/<slug:group_slug>/edit/', views.edit_group_attributes, name='edit_group_attributes'),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block meta %}<meta charset="UTF-8">{% endblock %}
    <title>Renova - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'base.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
	<script src="{% static 'javascript/jquery.js' %}"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
	{% block js %}{% endblock %}
</head>
<body>

<header>
    <!-- Logo -->
    <div id="logo" class="columns">
		<img src="{% static 'images/renova.png' %}" alt="Logo" />
    	RENOVA
    </div> 

    <nav>
        <ul>
		<!-- Outside the conditional statements, ALWAYS show -->
		<li><a href="{% url 'renova:index' %}">Home</a></li>
	{% if user.is_authenticated %}        	
		<!-- Show these links when the user is logged in -->
		<li><a href="{% url 'renova:my_logs' %}">My Logs</a></li>
        <li><a href="{% url 'renova:my_account' %}">My Account</a></li>
		<li><a href="{% url 'auth_logout' %}">Logout</a></li>
	{% else %}
		<!-- Show these links when the user is NOT logged in -->
		<li><a href="{% url 'registration_register' %}">Sign Up</a></li>
		<li><a href="{% url 'auth_login' %}">Login</a></li>
	{% endif %}
		<li><a href="{% url 'renova:groups' %}">Groups</a></li>
        </ul> 
    </nav>
</header>

<!-- Main Content -->
<main>
    {% block content %}
    {% endblock %}
</main>

<!-- Footer -->
<footer>
	<nav>
		<ul>
		<li><a href="{% url 'renova:about_us' %}">About Us</a></li>
		<li><a href="{% url 'renova:faq' %}">FAQ</a></li>
		</ul>
	</nav>
</footer>

</body>
</html>